version: '3'

services:
    web:
        build: .
        ports:
            - '5005:5000'
        volumes:
            - ./app:/usr/src/app/app
            - ./uploads:/usr/src/app/uploads
        depends_on:
            - redis
        environment:
            - FLASK_ENV=production

    redis:
        image: 'redis:alpine'
        ports:
            - '6179:6379'
